kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
  namespace: default
rules:
  - apiGroups: ["", "apps"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-role-binding
  namespace: default
subjects:
  - kind: User
    name: naruto
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
