kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
rules:
  - apiGroups: ["", "apps", "extensions", "autoscaling"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-cluster-role-binding
subjects:
  - kind: User
    name: naruto
roleRef:
  kind: ClusterRole
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
  namespace: playground
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-role-binding
  namespace: playground
subjects:
  - kind: User
    name: naruto
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io

