apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: long-job
              image: python:rc-slim
              command: ["python"]
              args:
                [
                  "-c",
                  "import time; print('Starting'); time.sleep(20); print('End')",
                ]
          restartPolicy: Never
      backoffLimit: 2
