apiVersion: batch/v1
kind: Job
metadata:
  name: jon
spec:
  template:
    spec:
      containers:
        - name: long-job
          image: python:rc-slim
          command: ["python"]
          args:
            [
              "-c",
              "import time; print('Starting'); time.sleep(20); print('End'); ",
            ]
      restartPolicy: Never
  backoffLimit: 2
